# Generated by Django 5.0.2 on 2024-07-13 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BeforeBuy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_1', models.CharField(max_length=55)),
                ('information_1', models.CharField(max_length=999)),
                ('title_2', models.CharField(max_length=55)),
                ('information_2', models.CharField(max_length=999)),
                ('title_3', models.CharField(max_length=55)),
                ('information_3', models.CharField(max_length=999)),
            ],
        ),
        migrations.CreateModel(
            name='FirstShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_1', models.CharField(max_length=55)),
                ('line_2', models.CharField(max_length=55)),
                ('line_3', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Profile_img', models.ImageField(upload_to='Personal')),
                ('First_Name', models.CharField(max_length=55)),
                ('Last_Name', models.CharField(max_length=55)),
                ('Nationality_ID', models.CharField(max_length=10)),
                ('Birthday', models.DateField(help_text='تاریخ تولد : مثال (12-12-1365)')),
                ('Phone_Number', models.CharField(max_length=11)),
                ('Email', models.CharField(max_length=255)),
                ('info_about_your_work', models.CharField(help_text='توضیحاتی درمورد رزومه خود', max_length=255)),
                ('desktop_photo', models.CharField(choices=[('Reza', 'Reza'), ('Defualt', 'Defualt')], max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(max_length=55)),
                ('Phone_Number', models.CharField(max_length=11)),
                ('Description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Social_Media', models.CharField(choices=[('ایمیل', 'ایمیل'), ('اینستاگرام', 'اینستاگرام'), ('تلگرام', 'تلگرام'), ('لیندکدین', 'لیندکدین'), ('توییتر', 'توییتر')], max_length=255)),
                ('Link', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='WhyChoose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_1', models.CharField(max_length=55)),
                ('information_1', models.CharField(max_length=255)),
                ('title_2', models.CharField(max_length=55)),
                ('information_2', models.CharField(max_length=255)),
                ('title_3', models.CharField(max_length=55)),
                ('information_3', models.CharField(max_length=255)),
                ('title_4', models.CharField(max_length=55)),
                ('information_4', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='WhyUPVC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=55)),
            ],
        ),
    ]
