# Generated by Django 5.0.7 on 2024-07-14 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeforeBuyCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='BeforeBuyOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='BeforeBuyWhyWindowmall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=55)),
            ],
        ),
        migrations.DeleteModel(
            name='BeforeBuy',
        ),
    ]
