# Generated by Django 5.0.7 on 2024-07-14 14:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_App', '0002_beforebuycost_beforebuyorder_beforebuywhywindowmall_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
