# Generated by Django 5.0.7 on 2024-07-13 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CV_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installed',
            name='Installed_Img',
            field=models.ImageField(help_text='لطفا سایز عکس یک در یک یا همان مربع باشد', upload_to='Personal'),
        ),
    ]
