# Generated by Django 5.0.7 on 2024-07-14 14:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CV_App', '0004_alter_comment_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='Active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 14, 14, 2, 25, 427286, tzinfo=datetime.timezone.utc)),
        ),
    ]
