# Generated by Django 5.0.2 on 2024-07-13 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(max_length=55)),
                ('Phone_Number', models.CharField(max_length=11)),
                ('window_number', models.IntegerField()),
                ('door_number', models.IntegerField()),
                ('Lace_number', models.IntegerField()),
                ('Postal_ID', models.CharField(blank=True, max_length=15, null=True)),
                ('Address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Costumer_Name', models.CharField(max_length=55)),
                ('Costumer_Phone', models.CharField(max_length=11)),
                ('Costumer_Address', models.CharField(max_length=255)),
                ('window_number', models.IntegerField()),
                ('door_number', models.IntegerField()),
                ('Lace_number', models.IntegerField()),
                ('Project_Price', models.IntegerField(blank=True, help_text='هزینه پروژه به تومان . مثال :\u200c 10500000', null=True)),
                ('Measurement_Date', models.DateField(blank=True, help_text='تاریخ اندازه گیری : مثال (12-12-1365)', null=True)),
                ('Start_Date', models.DateField(blank=True, help_text='تاریخ شروع پروژه : مثال (12-12-1365)', null=True)),
                ('Finish_Date', models.DateField(blank=True, help_text='تاریخ پایان پروژه : مثال (12-12-1365)', null=True)),
                ('Description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
