# Generated by Django 5.0.7 on 2024-07-14 14:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Measurement_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurementform',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 7, 14, 14, 2, 34, 814247, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
